[package]
name = "dirtio-http"
version = "0.1.0"
edition = "2021"

[dependencies]
dirtio = { git = "https://github.com/bsbds/dirtio.git" }

bytes = "1"
futures = "0.3"
http = "0.2"
httparse = "1.8"
httpdate = "1"
pin-project-lite = "0.2"
log = "0.4"
env_logger = "0.10"